# -*- coding: utf-8 -*-
"""Police.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T4gN45UTwYucsKs13Z0Rp0cq6KJJCb6D

**Police Dataset**

Here, 

The data from a Police Check Point is given
This data is available as a csv file. We are going to analyze this data set using the Pandas DataFrame
"""

import pandas as pd

data = pd.read_csv('/content/3. Police Data.csv')
data

"""**Instruction (For data cleaning)**

**1. Remove the column that only contains missing values**
"""

data.isnull().sum()

data.drop( columns = 'country_name' , inplace = True)

data

"""**Question ( Based on filtering + Value Counts )**

**2. For Speeding , were Men or Woman stopped more often ?**
"""

data.head()

data[data.violation == 'Speeding'].driver_gender.value_counts()

"""**Question ( Groupby )**

**3. Does gender affect who gets searched during a stop ?**
"""

data.head()

data.groupby('driver_gender').search_conducted.sum()

data.search_conducted.value_counts()

"""**Question ( mapping + data-type casting )**

**4. What is the mean stop_duration ?**
"""

data.head()

data.stop_duration.value_counts()

data['stop_duration'] = data['stop_duration'].map({'0-15 Min' : 7.5 , '16-30 Min' : 24 , '30+ Min' : 45} )

data

data['stop_duration'].mean()

"""**Question ( Groupby , Describe )**

**5. Compare the age distribution for each violation.**
"""

data.head()

data.groupby('violation').driver_age.describe()